<!DOCTYPE HTML PUBLIC “-//W3C//DTD HTML 4.01//EN” “http://www.w3.org/TR/html4/strict.dtd”>
<html>
<head>
<title>Thunderball Projektmanagement</title>

<?php

$script = 'var baseUrl = "' . $this->baseUrl() . '";';
echo $this->headScript()->appendScript($script);

echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/stylesheet.css');
echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/navigation.css');
echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/login.css');

echo $this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css');

echo '<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>';
echo '<script type="text/javascript" src="http://code.jquery.com/ui/1.9.1/jquery-ui.js"></script>';
echo '<script type="text/javascript" src="' . $this->baseUrl() . '/js/main.js"></script>';

// datatables
echo $this->headLink()->appendStylesheet($this->baseUrl() . '/datatables/css/demo_table_jui.css');
echo '<script type="text/javascript" src="' . $this->baseUrl() . '/datatables/js/jquery.dataTables.js"></script>';

// colorpicker
echo $this->headLink()->appendStylesheet($this->baseUrl() . '/colorpicker/jquery.colorpicker.css');
echo '<script type="text/javascript" src="' . $this->baseUrl() . '/colorpicker/jquery.colorpicker.js"></script>';

// notifier
echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery.notify.css');
echo '<script type="text/javascript" src="' . $this->baseUrl() . '/js/jquery.notify.js"></script>';

?>

<script type="text/javascript">
$(function() {
	$('#logout-button').click(function(){
		window.location = baseUrl + '/account/logout';
	});

	$("#container").notify();

	<?= $this->message ?>
	
});
</script>

</head>
<body>
	
	<div id="container" style="display: none">
		<div id="basic-template">
			<a class="ui-notify-cross ui-notify-close" href="#">x</a>
			<h1>#{title}</h1>
			<p>#{text}</p>
		</div>
	</div>

	<div id="wrapper">
		<div id="container">

			<div style="text-align: right; padding-top: 5px;">
			<?php
			if ($this->accountHelper()->userIsLoggedIn()) {
				echo '<a href="' . $this->baseUrl() . '/index/help">Hilfe</a>';
			} else { echo "&nbsp;"; }
			?>
			</div>

			<div style="padding-bottom: 60px">
				<div id="byscnet_logo"></div>
				<div style="text-align: right">
					<h1>Thunderball Project Payment</h1>
				</div>
				<div id="navbar">
				<?= $this->navigation()->menu()->renderMenu(null, array('minDepth' => 0, 'maxDepth' => 0,)); ?>
					<span id="loginLink"> <?php 
					if ($this->accountHelper()->userIsLoggedIn()) {
						echo '<a href="#" id="logout-button">Abmelden</a>';
						echo '<span id="logged-in-user">';
						echo $this->accountHelper()->getSalutation();
						echo '&nbsp;&nbsp;|</span>';
					} else {
						echo '<a href="#login-box" class="login-window" id="login-button">Anmelden</a>';
					}
					?> </span>
				</div>
				<div id="subnavbar">
				<?= $this->navigation()->menu()->renderMenu(null, array('minDepth' => 1, 'maxDepth' => 1, 'onlyActiveBranch' => true, 'renderParents' => false)); ?>
				</div>
			</div>



			<div style="background-color: #fafafa; padding-bottom: 20px;">
			<?php echo $this->layout()->content; ?>
			</div>


		</div>
	</div>
	<div id="footer">
		Copyright &copy;
		<?=date('Y');?>
		<a href="http://www.byscnet.de/" target="_new"> byscnet.de -
			OpenSource Solutions</a>
	</div>
	<div id="login-box" class="login-popup">
		<a href="#" class="close"><img
			src="<?= $this->baseUrl() ?>/img/close_pop.png" class="btn_close"
			title="Close Window" alt="Close" /> </a>
		<form method="post" name="loginForm" class="signin"
			action="<?= $this->baseUrl() ?>/account/login">
			<fieldset class="textbox">
				<label class="username"> <span>E-Mail:</span> <input id="username"
					name="username" value="" type="text" autocomplete="on"
					placeholder="E-Mail"> </label> <label class="password"> <span>Passwort:</span>
					<input id="password" name="password" value="" type="password"
					placeholder="Passwort"> </label>
				<button class="submit button" type="button"
					onclick="document.loginForm.submit()">Anmelden</button>
				<p>
					<a class="forgot" href="<?= $this->baseUrl() ?>/account/lost-pwd">Haben
						Sie Ihr Passwort vergessen?</a>
				</p>
			</fieldset>
		</form>
	</div>


</body>
</html>
