<?= $this->layoutHelper()->getHeadline('Neuen Kunden anlegen', array('btnCancel' => 'Abbrechen', 'btnSave' => 'Speichern')) ?>

<script>
$(document).ready(function(){
	
	$('#btnSave').button({icons: {primary: "ui-icon-disk"}, text: true}).click(function(){
		$('#newCustomerForm').submit();
	});

	$('#btnCancel').button({icons: {primary: "ui-icon-close"}, text: true}).click(function(){
		window.location = baseUrl + "/customer/";
	});

	
});
</script>

<div class="content">
	<form method="post" id="newCustomerForm">
		<table width="900">
			<tr>
				<td valign="top"><?= $this->form->company ?>
				</td>
				<td valign="top"><?= $this->form->name ?>
				</td>
				<td valign="top" rowspan="2"><?= $this->form->description ?>
				</td>
			</tr>
			<tr>
				<td valign="top"><?= $this->form->new_company ?></td>
			</tr>
		</table>
	</form>
	<?= $this->layoutHelper()->getNotOptionalInfo() ?>
</div>
