<?= $this->layoutHelper()->getHeadline('Projekt bearbeiten', array('btnCancel' => 'Abbrechen', 'btnSave' => 'Änderungen speichern')) ?>

<script>
$(function() {
$('#start_date').datepicker();
$('#end_date').datepicker();
$('#planed_end_date').datepicker();
$('#booking_blocked_till').datepicker();
$('#garantee_till').datepicker();
$("#colour").colorpicker();

$( "#btnSave" ).button({icons: {primary: "ui-icon-disk"}, text: true}); 
$('#btnSave').click(function(){$('#editProjectForm').submit();});
$('#btnCancel').button({icons: {primary: "ui-icon-close"}, text: true}).click(function(){history.back();});
});
</script>

<form method="post" id="editProjectForm">
<div style="padding: 10px">
	<table width="900">
		<tr>
			<td valign="top">
			<?= $this->form->name ?> 
			<?= $this->form->parent ?> 
			<?= $this->form->description ?>
			<?= $this->form->notice ?>
			</td>
			<td valign="top">
			<?= $this->form->status ?>
			<?= $this->form->customer ?>
			<?= $this->form->category ?>
			<?= $this->form->risk ?>
			<?= $this->form->colour ?>
			</td>
			<td valign="top">
			<?= $this->form->start_date ?>
			<?= $this->form->end_date ?>
			<?= $this->form->planed_end_date ?>
			<?= $this->form->booking_blocked_till ?>
			<?= $this->form->garantee_till ?>
			</td>
		</tr>
	</table>
<?= $this->layoutHelper()->getNotOptionalInfo() ?>
</div>
	
</form>








