<?= $this->layoutHelper()->getHeadline('Projektübersicht', array()) ?>

<script>



$(document).ready(function(){
	oTable = $('#projectlist').dataTable({
		"bJQueryUI": true,
		"sPaginationType": "full_numbers",
		"bProcessing": true,
		"sDom": '<"H"lfr>t<"F"ip>',
		"bServerSide": true,
		"bStateSave": true,
		"sAjaxSource": baseUrl + "/project-ajax/list",
		"aoColumns" : [null, null, null, null, null, null, {"bSortable": false}],
		"fnDrawCallback": function () {  
			$( ".btnEdit" ).button({icons: {primary: "ui-icon-wrench"}, text: false}); 
			$( ".btnDelete" ).button({icons: {primary: "ui-icon-trash"}, text: false}); 
			$( ".btnDetail" ).button({icons: {primary: "ui-icon-document"}, text: false}); 
			},
		"oLanguage": {
			"sLengthMenu": "_MENU_ pro Seite anzeigen",
			"sZeroRecords": "Keine Projekte gefunden",
			"sInfo": "Zeige _START_ bis _END_ von insgesammt _TOTAL_ Projekte",
			"sInfoEmpty": "Es werden keine Projekte angezeigt",
			"sInfoFiltered": "(gefiltert von insgesammt _MAX_ Projekte)",
			"sSearch": "Suche:"}
	});
});

function editItem(itemId)
{
	window.location = baseUrl + "/project/edit/id/" + itemId;
}

function deleteItem(itemId)
{
	window.location = baseUrl + "/administration/user-delete/id/" + itemId;
}

function showItem(itemId)
{
	window.location = baseUrl + "/project/detail/id/" + itemId;
}

</script>


<table id="projectlist" cellpadding="0" cellspacing="0" border="0"
	class="display" style="width: 100%">
	<thead>
		<tr>
			<th></th>
			<th>Name</th>
			<th>Kategorie</th>
			<th>Start</th>
			<th>Kunde</th>
			<th>Status</th>
			<th width="150">Options</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td colspan="7" class="dataTables_empty">Loading data from server</td>
		</tr>
	</tbody>
</table>