<?= $this->layoutHelper()->getHeadline('Stunden erfassen', array('addHour' => 'Stunden buchen')) ?>

<script>



$(function() {

	oTable = $('#hourlist').dataTable({
		"bJQueryUI": true,
		"bPaginate": false,
		"bProcessing": true,
		"sDom": '<"H"lr>t<"F"p>',
		"bServerSide": true,
		"bStateSave": true,
		"sAjaxSource": baseUrl + "/hour-ajax/list",
		"aoColumns" : [null, null, null, null, null, {"bSortable": false}],
		"fnDrawCallback": function () {  
			//$( ".btnEdit" ).button({icons: {primary: "ui-icon-wrench"}, text: false}); 
			$( ".btnDelete" ).button({icons: {primary: "ui-icon-trash"}, text: false}); 
			//$( ".btnDetail" ).button({icons: {primary: "ui-icon-document"}, text: false}); 
			},
		"oLanguage": {
			"sLengthMenu": "_MENU_ pro Seite anzeigen",
			"sZeroRecords": "Keine Stunden gebucht",
			"sInfo": "Zeige _START_ bis _END_ von insgesammt _TOTAL_ Stunden",
			"sInfoEmpty": "Es werden keine Stunden angezeigt",
			"sInfoFiltered": "(gefiltert von insgesammt _MAX_ Stunden)",
			"sSearch": "Suche:"}
	});

	$('#package').empty().append('<option selected="selected">Bitte Projekt auswählen</option>');

	
$('#date').datepicker({ dateFormat: "dd.mm.yy" });

$( "#addHour" ).button({icons: {primary: "ui-icon-disk"}, text: true}).click(function(){
	var projectId = $('#project').val();
	var packageId = $('#package').val();
	var hours = $('#hours').val();
	var date = $('#date').val();
	var notice = $('#notice').val();

	if (!(projectId > 0)) {
		alert('Bitte wählen Sie ein Projekt aus');
		return false;
	}

	if (!(packageId > 0)) {
		alert('Bitte wählen Sie ein Arbeitspaket aus');
		return false;
	}

	// TODO check hours
	// TODO check date
	
	var params = {
			'projectId': projectId,
			'packageId': packageId,
			'hours': hours,
			'date': date,
			'notice': notice,
			'mode': 'add'
	};

	post('hour-ajax', 'manage-hours', params, function(data){

		if (data == 0) {
			alert('Beim Buchen der Stunden ist ein Fehler aufgetreten. Bitter überprüfen Sie Ihre Angaben.');
			return false;
		} else if (data == 2) {
			alert('Es sind nicht genügend Stunden für dieses Arbeitspaket verfügbar.');
			return false;
		}

		updateHourInfo(packageId, projectId);
	});

	
	oTable.fnReloadAjax();
	
	return false;
});

});

function deleteItem(itemId)
{
	if (confirm('Wollen Sie die Stunden wirklich löschen'))
	{
		var params = {
				'hoursId': itemId,
				'mode': 'remove'
		};
		
		post('hour-ajax', 'manage-hours', params, function(data){

			if (data == 0) {
				alert('Beim Löschen ist ein Fehler aufgetreten.');
				return false;
			} 

			updateHourInfo($('#package').val(), $('#project').val());
		});

		oTable.fnReloadAjax();
	}
}

function projectOnChange(projectId)
{
	oTable.fnReloadAjax(baseUrl + '/hour-ajax/list/projectId/' + projectId);
	
	post('hour-ajax', 'list-package', {'projectId': projectId}, function(data){
		var mySelect = $('#package');
		$('#package').empty().append('<option selected="selected">Bitte wählen</option>');
		$.each(data, function(val, text) {
		    mySelect.append(
		        $('<option></option>').val(val).html(text)
		    );
		});
		});
}

function packageOnChange(packageId)
{
	oTable.fnReloadAjax(baseUrl + '/hour-ajax/list/projectId/' + $('#project').val() + '/packageId/' + packageId);

	updateHourInfo(packageId, $('#project').val());
}

function updateHourInfo(packageId, projectId)
{
	post('hour-ajax', 'hour-info', {'projectId': projectId, 'packageId': packageId}, function(data){
		$('#hourInfo').html(data);
		
	});
}

</script>

<div class="content">
<form method="post" id="newHourForm">
	<div style="margin-bottom: 50px;">
		<table width="600">
			<tr>
				<td valign="top"><?= $this->form->project ?>
				</td>
				<td valign="top"><?= $this->form->hours ?>
				</td>
			</tr>
			<tr>
				<td valign="top"><?= $this->form->package ?>
				</td>
				<td valign="top"><?= $this->form->date ?>
				</td>
			</tr>
			<tr>
				<td valign="top" colspan="2"><?= $this->form->notice ?></td>
			</tr>
		</table>
		<?= $this->layoutHelper()->getNotOptionalInfo() ?>
	</div>
</form>

<div style="padding-bottom: 10px;" id="hourInfo"></div>

<table id="hourlist" cellpadding="0" cellspacing="0" border="0"
	class="display" style="width: 100%">
	<thead>
		<tr>
			<th>Datum</th>
			<th>Stunden</th>
			<th>Project</th>
			<th>Arbeitspaket</th>
			<th>Bemerkung</th>
			<th width="150">Optionen</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td colspan="7" class="dataTables_empty">Loading data from server</td>
		</tr>
	</tbody>
</table>


</div>





