<?= $this->layoutHelper()->getHeadline('Einführung', array()) ?>

<div class="content">

	<table style="width: 100%">
		<tr>
			<td style="width: 50%; text-align: justify; padding-right: 25px;" valign="top">
				<h4>Was ist Thunderball Project Payment?</h4>
				<p>Thunderball Project Payment ist ein Open Source Tool zur
					Erfassung und Auswertung geleisteter Stunden für ein Projekt.</p> <br />
				<h4>Wie funktioniert Thunderball Project Payment?</h4>
				<p>Mit Thunderball Project Payment können Sie durch die Entwickler
					oder Projektleiter definierten Arbeitspakete (wie z.B. Planung,
					Dokumentation, Implementierung oder Test) für ein Projekt
					verwalten.</p>
				<p>Durch tägliche Buchung der geleisteten Stunden für ein Projekt
					behält der Projektleiter stets eine genaue Übersicht des
					veranschlagten Budgets und kann sofort reagieren, sobald ein
					gewisses Kontingent an Stunden für ein Arbeitspaket erschöpft ist.</p>
			</td>


			<td style="width: 50%" valign="top; text-align: justify">
				<h4>Woher bekomme ich Thunderball Project Payment?</h4>
				<p>
					Thunderball Project Payment wird auf der Plattform <i>github</i>
					gehostet:
				</p>
				<p>
					github: <a href="https://github.com/byscnet/thunderball"
						target="_new">https://github.com/byscnet/thunderball</a>
				</p>
				<p>Dort erhalten Sie den Download und Hilfe bei der Installation.</p>
				<br />
				<h4>Was kostet Thunderball Project Payment?</h4>
				<p>Die Benutzung von Thunderball Project Payment ist kostenlos.</p>
				<br />
				<h4>Woher bekomme ich Support?</h4>
				<p>
					Sollten Sie Probleme bei der Benutzung von Thunderball Project
					Payment feststellen, können Sie diese uns auf <i>github</i> unter
					"<a href="https://github.com/byscnet/thunderball/issues" target="_new">issues</a>" mitteilen.<br />
					Dieser Support ist für Sie kostenlos.
				</p>
			</td>
		</tr>

		<tr>

		</tr>

	</table>






</div>
