<?= $this->layoutHelper()->getHeadline('Einführung', array()) ?>

<div class="content">

	<table style="width: 100%">
		<tr>
			<td style="width: 50%; text-align: justify; padding-right: 25px;"
				valign="top">
				<h4>Was ist Thunderball Project Payment?</h4>
				<p>Thunderball Project Payment ist ein Open Source Tool zur
					Erfassung und Auswertung geleisteter Stunden für ein Projekt.</p> <br />
				<h4>Warum Thunderball Project Payment?</h4>
				<p>Viele Programme zur Abrechnung von Projektkosten sind völlig
					überladen an Funktionen und erfordern viel Geduld beim Anwender.
					Thunderball hingegen kommt mit einer klar strukturierten Oberfläche
					daher, die dem Anwender eine intuitive Bedienung ermöglicht.</p>
				<p>
					Der Quellcode dieses Projekts ist außerdem frei verfügbar und kann
					daher auf die eigenen Bedürfnisse angepasst werden.<br />
					Gerne übernehmen auch wir das für Sie! Sollten Sie spezielle
					Änderungs- und/oder Erweiterungswünsche haben, nehmen Sie einfach
					mit uns Kontakt auf: <a href="mailto:hotline@byscnet.de">hotline@byscnet.de</a>.
				</p> <br />
				<h4>Wie funktioniert Thunderball Project Payment?</h4>
				<p>Mit Thunderball Project Payment können Sie durch die Entwickler
					oder Projektleiter definierten Arbeitspakete (wie z.B. Planung,
					Dokumentation, Implementierung oder Test) für ein Projekt
					verwalten.</p>
				<p>Durch tägliche Buchung der geleisteten Stunden für ein Projekt
					behält der Projektleiter stets eine genaue Übersicht des
					veranschlagten Budgets und kann sofort reagieren, sobald ein
					gewisses Kontingent an Stunden für ein Arbeitspaket erschöpft ist.</p>

			</td>


			<td style="text-align: justify; width: 50%" valign="top">
				<h4>Woher bekomme ich Thunderball Project Payment?</h4>
				<p>
					Thunderball Project Payment wird auf der Plattform <i>github</i>
					gehostet:
				</p>
				<p>
					github: <a href="https://github.com/byscnet/thunderball"
						target="_new">https://github.com/byscnet/thunderball</a>
				</p>
				<p>Dort erhalten Sie den Download und Hilfe bei der Installation.</p>
				<br />
				<h4>Was kostet Thunderball Project Payment?</h4>
				<p>
					Dieses Projekt steht unter der GPL Lizens. Die Benutzung ist daher
					kostenlos. <br /> Mehr Informationen finden Sie unter <a
						href="http://www.gnu.org/licenses/gpl.html" target="_new">http://www.gnu.org/licenses/gpl.html</a>
				</p> <br />
				<h4>Woher bekomme ich Support?</h4>
				<p>
					Sollten Sie Probleme bei der Benutzung von Thunderball Project
					Payment feststellen, können Sie diese uns auf <i>github</i> unter "<a
						href="https://github.com/byscnet/thunderball/issues" target="_new">issues</a>"
					mitteilen.<br /> Dieser Support ist für Sie kostenlos.
				</p>
			</td>
		</tr>

		<tr>

		</tr>

	</table>






</div>
